### ISSUE TITLE
Failed Initilization 

### ISSUE THREAD

**Issue by denisanix** [KiraCore/testnet#28]
Following steps for install:
- run script
- branch: testnet-2
- set [A] autodiscover, i get the latest snap, which is dwld
- rest of setups runs ok, no errors
- multiple fresh instal, always end up in the error attached

![Screenshot 2021-04-18 214822](https://user-images.githubusercontent.com/81810153/115250261-13597a80-a132-11eb-8db3-840b6f2fe6ee.jpg)

**Comment by MrLutik** [comment]
@denisanix Please check the pinned message in Telegram https://t.me/kiratesters

After investigating current state of testnet-2 the Public Testnet will be re-started shortly after as testnet-3. We will update everyone once connecting to testnet-3 will become possible.

Those who already managed to connect to testnet-2 and didn't stopped their machines yet have opportunity to submit issue reports to relevant github repositories followed by sending link to relevant submission form.

If your KYC passed then you will not have to submit it again or otherwise reapply and once you deploy your validator on the testnet-3 it will have a WAITING status. To learn about status of your KYC contact support.kira.network.

Details for issues submission: https://medium.com/kira-core/kira-launches-public-testnet-df5bcad028b8

**Comment by asmodat** [comment]
Should be resolved with v0.3.2.3
