### ISSUE TITLE
Interx Errors in latest testnet

### ISSUE THREAD

**Issue by valNodeOne** [KiraCore/testnet#29]
There are multiple errors for nearly every block in the interx log:

ERROR: 2021/04/19 13:08:14 [rpc-call] Block not found: 204119
ERROR: 2021/04/19 13:08:19 [AddNewBlock] block just after a halt: 204118, timestamp: 62.070832, average: 13.457605
ERROR: 2021/04/19 13:08:54 [AddNewBlock] not a new block: 204120
...

**Comment by MrLutik** [comment]
@valNodeOne Please check the pinned message in Telegram https://t.me/kiratesters

After investigating current state of testnet-2 the Public Testnet will be re-started shortly after as testnet-3. We will update everyone once connecting to testnet-3 will become possible.

Those who already managed to connect to testnet-2 and didn't stopped their machines yet have opportunity to submit issue reports to relevant github repositories followed by sending link to relevant submission form.

If your KYC passed then you will not have to submit it again or otherwise reapply and once you deploy your validator on the testnet-3 it will have a WAITING status. To learn about status of your KYC contact support.kira.network.

Details for issues submission: https://medium.com/kira-core/kira-launches-public-testnet-df5bcad028b8

**Comment by asmodat** [comment]
Should be resolved with v0.3.2.3
