### ISSUE TITLE
Testnet-2 INFRASTRUCTURE IS UNHEALTHY, [R] | RESTART All Containers nothing changed

### ISSUE THREAD

**Issue by goganaut** [KiraCore/testnet#32]
BLOCK: 204503 
![изображение](https://user-images.githubusercontent.com/82846245/115307260-4a6c7200-a1ac-11eb-853f-eff1bdee6d9c.png)
DUMP All Loggs

[first_timeunhealthy_kira.zip](https://github.com/KiraCore/testnet/files/6339371/first_timeunhealthy_kira.zip)
unhealthy on block 202991, logs before restart, work fine after restart
then
[kira.zip](https://github.com/KiraCore/testnet/files/6339298/kira.zip) -- before RESTART
unhealthy on block 204503 logs, RESTART All Containers nothing changed
[after_R_kira.zip](https://github.com/KiraCore/testnet/files/6339330/after_R_kira.zip) -- after RESTART

**Comment by MrLutik** [comment]
@goganaut Please check the pinned message in Telegram https://t.me/kiratesters

After investigating current state of testnet-2 the Public Testnet will be re-started shortly after as testnet-3. We will update everyone once connecting to testnet-3 will become possible.

Those who already managed to connect to testnet-2 and didn't stopped their machines yet have opportunity to submit issue reports to relevant github repositories followed by sending link to relevant submission form.

If your KYC passed then you will not have to submit it again or otherwise reapply and once you deploy your validator on the testnet-3 it will have a WAITING status. To learn about status of your KYC contact support.kira.network.

Details for issues submission: https://medium.com/kira-core/kira-launches-public-testnet-df5bcad028b8

**Comment by asmodat** [comment]
Resolved with v0.3.2.3 - `testnet-3`
