### ISSUE TITLE
Waiting snapshot 

### ISSUE THREAD

**Issue by hoanghiepluc** [KiraCore/testnet#34]
**I waited 6 hours. It is not completed**

+ '[' '!' -d /home/hh/snap/testnet-2-204503-1618966514 ']'
+ i=142
+ cat /docker/shared/common/sentry/logs/start.log
+ tail -n 10
2:05AM INF Served RPC HTTP response duration=0 method=GET module=rpc-server remoteAddr=10.2.0.1:33082 status=200 url={"ForceQuery":false,"Fragment":"","Host":"","Opaque":"","Path":"/status","RawFragment":"","RawPath":"","RawQuery":"","Scheme":"","User":null}
2:05AM INF Served RPC HTTP response duration=0 method=GET module=rpc-server remoteAddr=10.2.0.1:33092 status=200 url={"ForceQuery":false,"Fragment":"","Host":"","Opaque":"","Path":"/status","RawFragment":"","RawPath":"","RawQuery":"","Scheme":"","User":null}
2:05AM INF Served RPC HTTP response duration=0 method=GET module=rpc-server remoteAddr=10.2.0.1:33102 status=200 url={"ForceQuery":false,"Fragment":"","Host":"","Opaque":"","Path":"/status","RawFragment":"","RawPath":"","RawQuery":"","Scheme":"","User":null}
2:05AM INF Served RPC HTTP response duration=0 method=GET module=rpc-server remoteAddr=10.2.0.1:33112 status=200 url={"ForceQuery":false,"Fragment":"","Host":"","Opaque":"","Path":"/status","RawFragment":"","RawPath":"","RawQuery":"","Scheme":"","User":null}
2:05AM INF Served RPC HTTP response duration=0 method=GET module=rpc-server remoteAddr=10.2.0.1:33122 status=200 url={"ForceQuery":false,"Fragment":"","Host":"","Opaque":"","Path":"/status","RawFragment":"","RawPath":"","RawQuery":"","Scheme":"","User":null}
2:05AM INF Served RPC HTTP response duration=0 method=GET module=rpc-server remoteAddr=10.2.0.1:33132 status=200 url={"ForceQuery":false,"Fragment":"","Host":"","Opaque":"","Path":"/status","RawFragment":"","RawPath":"","RawQuery":"","Scheme":"","User":null}
2:05AM INF Served RPC HTTP response duration=0 method=GET module=rpc-server remoteAddr=10.2.0.1:33142 status=200 url={"ForceQuery":false,"Fragment":"","Host":"","Opaque":"","Path":"/status","RawFragment":"","RawPath":"","RawQuery":"","Scheme":"","User":null}
2:05AM INF HTTPJSONRPC args=[{}] method=status module=rpc-server returns=[{},{}]
2:05AM INF Served RPC HTTP response duration=0 method=POST module=rpc-server remoteAddr=127.0.0.1:54696 status=200 url={"ForceQuery":false,"Fragment":"","Host":"","Opaque":"","Path":"/","RawFragment":"","RawPath":"","RawQuery":"","Scheme":"","User":null}
2:05AM INF Served RPC HTTP response duration=0 method=GET module=rpc-server remoteAddr=10.2.0.1:33154 status=200 url={"ForceQuery":false,"Fragment":"","Host":"","Opaque":"","Path":"/status","RawFragment":"","RawPath":"","RawQuery":"","Scheme":"","User":null}
+ echoInfo 'INFO: Waiting for snapshot '\''testnet-2-204503-1618966514'\'' to be created...'
+ echo -e '\e[0m\e[36;1mINFO: Waiting for snapshot '\''testnet-2-204503-1618966514'\'' to be created...\e[0m'
INFO: Waiting for snapshot 'testnet-2-204503-1618966514' to be created...
+ sleep 30

**Comment by MrLutik** [comment]
@hoanghiepluc  Please check the pinned message in Telegram https://t.me/kiratesters

After investigating current state of testnet-2 the Public Testnet will be re-started shortly after as testnet-3. We will update everyone once connecting to testnet-3 will become possible.

Those who already managed to connect to testnet-2 and didn't stopped their machines yet have opportunity to submit issue reports to relevant github repositories followed by sending link to relevant submission form.

If your KYC passed then you will not have to submit it again or otherwise reapply and once you deploy your validator on the testnet-3 it will have a WAITING status. To learn about status of your KYC contact support.kira.network.

Details for issues submission: https://medium.com/kira-core/kira-launches-public-testnet-df5bcad028b8

**Comment by asmodat** [comment]
Resolved with v0.3.2.3 - `testnet-3`
